# Taps
tap "aquasecurity/trivy"
tap "cockroachdb/tap"
tap "dkanejs/aws-session-manager-plugin"
tap "go-delve/delve"
tap "goreleaser/tap"
# tap "habitat-sh/habitat"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "kishaningithub/tap"
tap "kyoh86/tap"
tap "mike-engel/jwt-cli"
tap "mingrammer/flog"
tap "potatolabs/git-redate"
tap "rs/tap"
tap "saulpw/vd"
tap "sonatype-nexus-community/nancy-tap"
tap "teamookla/speedtest"
tap "thecasualcoder/stable"
tap "tomanthony/brews"
tap "tylerbrock/saw"

# cli commands
brew "age"
brew "webp"
brew "openssl@1.1"
brew "aria2"
brew "gdbm"
brew "gettext"
brew "sqlite"
brew "python@3.9"
brew "glib"
brew "python@3.8"
brew "atk"
brew "autoconf"
brew "autojump"
brew "automake"
brew "avro-tools"
brew "awscli"
brew "bat"
brew "bdw-gc"
brew "bfg"
brew "browser"
brew "fontconfig"
brew "pkg-config"
brew "libx11"
brew "cairo"
brew "gcc"
brew "tbb"
brew "ceres-solver"
brew "cloog"
brew "cmake"
brew "cmatrix"
brew "faad2"
brew "flac"
brew "libtool"
brew "libidn2"
brew "unbound", restart_service: true
brew "gobject-introspection"
brew "harfbuzz"
brew "libass"
brew "libvorbis"
brew "srt"
brew "tesseract"
brew "jemalloc"
brew "libcue"
brew "nghttp2"
brew "cmus"
brew "cocoapods"
brew "consul", restart_service: true
brew "coreutils"
brew "direnv"
brew "dive"
brew "elinks"
brew "fftw"
# brew "fluent-bit"
brew "folly"
brew "fzf"
brew "gcc@4.9", link: false
brew "gdk-pixbuf"
brew "git"
brew "gsettings-desktop-schemas"
brew "glib-networking"
brew "gmic"
brew "go"
brew "goaccess"
brew "golangci-lint"
brew "gradle"
# brew "grafana", restart_service: true
brew "graphicsmagick"
brew "pango"
brew "graphviz"
brew "helm"
brew "hexyl"
brew "htop"
brew "httpie"
brew "httpstat"
brew "httrack"
brew "hugo"
brew "hyperfine"
brew "ideviceinstaller"
brew "imagemagick"
brew "ios-deploy"
brew "iproute2mac"
brew "jenv"
brew "jid"
brew "oniguruma"
brew "jq"
brew "k6"
# brew "kafka", restart_service: true
brew "kcat"
brew "krb5"
brew "kubernetes-cli", link: false
brew "libgpg-error"
brew "libgcrypt"
brew "libksba"
brew "libpq"
brew "libraqm"
brew "libsoup"
brew "libuv"
brew "libxml2"
brew "libxslt"
brew "libyaml"
brew "lzip"
brew "node"
brew "marp-cli"
brew "maven"
brew "meson"
brew "micro"
brew "midnight-commander"
brew "mkcert"
brew "montage"
brew "msgpack"
brew "ncdu"
brew "neovim"
brew "nnn"
brew "nss"
brew "ntfs-3g"
brew "numpy"
brew "nvm"
brew "pybind11"
brew "ocrmypdf"
brew "protobuf"
brew "opencv"
brew "openjdk@11"
brew "pandoc"
brew "parallel"
brew "pgcli"
brew "pidcat"
brew "pipenv"
brew "poetry"
brew "pre-commit"
brew "proftpd", restart_service: true
# brew "prometheus", restart_service: true
brew "pstree"
brew "pv"
brew "qt"
brew "pyqt"
brew "python@2", link: false
# brew "qcachegrind"
brew "rclone"
# brew "redis", restart_service: true
brew "ripgrep"
brew "rpm"
brew "ruby"
brew "sbt"
brew "scala"
brew "sip"
brew "sl"
brew "sphinx-doc"
brew "sqldiff"
# brew "stunnel", restart_service: true # Originally used for making redis connect via tls, now redis cli supports tls
brew "telnet"
brew "terraform"
brew "tesseract-lang"
brew "textql"
# brew "the_silver_searcher"
brew "tig"
brew "tldr"
brew "tmux"
# brew "travis"
brew "tree"
brew "ttyplot"
brew "tz"
brew "unixodbc"
brew "vala"
# brew "vegeta"
brew "w3m"
brew "watch"
brew "watchman"
# brew "watson"
brew "wget"
brew "wrk"
brew "wxwidgets"
brew "youtube-dl"
brew "yq"
brew "zlib"
brew "aquasecurity/trivy/trivy"
# brew "cockroachdb/tap/cockroach"
brew "dkanejs/aws-session-manager-plugin/aws-session-manager-plugin"
# brew "goreleaser/tap/goreleaser"
# brew "hashicorp/tap/vault"
brew "kishaningithub/tap/dynamodb-backup-restore"
brew "kishaningithub/tap/dynamodb-clone"
brew "kishaningithub/tap/kafka-console-avro-without-schema-registry"
brew "kishaningithub/tap/kafka-perf"
brew "kishaningithub/tap/memory-eater"
brew "kishaningithub/tap/randomtext"
brew "kishaningithub/tap/shopify-csv-download"
brew "kyoh86/tap/richgo"
# brew "mike-engel/jwt-cli/jwt-cli"
# brew "mingrammer/flog/flog"
# brew "potatolabs/git-redate/git-redate"
# brew "rs/tap/jaggr"
# brew "rs/tap/jplot"
# brew "saulpw/vd/visidata"
# brew "teamookla/speedtest/speedtest"
# brew "thecasualcoder/stable/gg"
# brew "tomanthony/brews/itermocil"
# brew "tylerbrock/saw/saw"

# GUI
cask "adobe-acrobat-reader"
cask "alt-tab"
# cask "android-studio"
# cask "background-music" # Changes default audio output and helps control volume of various apps.
cask "docker"
cask "drawio"
cask "dropbox"
cask "evernote" # TODO: Move contents from evernote to joplin
cask "ferdi"
# cask "flutter" # Not using it
# cask "flycut" # clip board manager Not very pleased with this one
cask "gimp"
cask "handbrake"
cask "imageoptim"
cask "intellij-idea"
cask "jd-gui"
cask "joplin"
# cask "jumpcut" # clip board manager Not very pleased with this one
cask "keepassxc"
cask "libreoffice"
# cask "licecap" # Good screen capturer using gif
# cask "mysqlworkbench" # Not actively using it
cask "osxfuse"
# cask "owasp-zap"
# cask "postman"
cask "shiftit"
# cask "skype"
cask "slack"
cask "stats"
# cask "sublime-text"
# cask "superproductivity" # Useful todo list app but not an active user
# cask "teamviewer"
cask "tor-browser"
cask "transmission"
# cask "vagrant"
# cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
# cask "xmind"
cask "xquartz" # Needed by gimp
cask "zoom"
